### ISSUE TITLE
Try to manually import OVF file to EC2

### ISSUE THREAD

**Issue by Dorajia** [Dorajia/CMPE283-Project#15]

**Comment by MiaoS** [comment]
Review the prerequisites. For more information, see Prerequisites.
Install the AWS CLI on your virtual machine to import it to Amazon EC2. For more information, see Installing the AWS Command Line Interface in the AWS Command Line Interface User Guide.
Disable any antivirus or intrusion detection software on your VM. These services can be re-enabled after the import process is complete.
Uninstall the VMware Tools from your VMware VM.
Disconnect any CD-ROM drives (virtual or physical).
Set your network to DHCP instead of a static IP address. If you want to assign a static private IP address, be sure to use a non-reserved private IP address in your VPC subnet. Amazon Virtual Private Cloud (Amazon VPC) reserves the first four private IP addresses in a VPC subnet.
Shut down your VM before exporting it.

**Comment by Dorajia** [comment]
1.  If want to SSH on VM, must know the IP address of VM, if want to know the ip address of VM, VM must install VM tools.
   If VM tools are not installed, then provide script to let user run it on VM to install EC2 CLI
   vim-cmd vmsvc/get.summary 1 | egrep '(power|ip)' 
2.  Download and install the CLI tools
   Install Java JDK 1.7 or later
   Set CLI tool
3.  Enable Secure Shell (SSH) for remote access. 
   https://help.ubuntu.com/community/SSH/OpenSSH/Configuring 
4.  Make sure that your host firewall (such as Linux iptables) allows access to SSH. 
5.  Make sure that you have configured a non-root user to use public key-based SSH to access your instance after it is imported. 
   https://www.digitalocean.com/community/tutorials/how-to-create-a-sudo-user-on-ubuntu-quickstart
   http://askubuntu.com/questions/115151/how-to-setup-passwordless-ssh-access-for-root-user 
   http://superuser.com/questions/530016/ssh-rsa-key-with-non-root-user 
6.  Uninstall the VMware Tools from your VMware VM. 
7.  Disconnect any CD-ROM drives (virtual or physical). 
8.  Set your network to DHCP instead of a static IP address. If you want to assign a static private IP address, be sure to use a non-reserved private IP address in your VPC subnet. Amazon Virtual Private Cloud (Amazon VPC) reserves the first four private IP addresses in a VPC subnet. 
9.  Shut down your VM before exporting it. 
10. Import command: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/model/ImportInstanceRequest.html 
    http://stackoverflow.com/questions/27252114/aws-import-vmdk-java
    http://grepcode.com/file/repo1.maven.org/maven2/com.amazonaws/aws-android-sdk-s3/2.1.7/com/amazonaws/services/ec2/model/ImportInstanceRequest.java 

seems the Java api is not well documented, so will consider EC2-CLI
